# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

format= """
[](bg:black fg:#303030)\
$username\
$hostname\
[](fg:#303030 bg:#444444)\
$directory\
[](fg:#444444 bg:#053354)\
$git_branch\
$git_metrics\
$git_status\
[](fg:#053354 bg:black)
$character"""

# Inserts a blank line between shell prompts
add_newline = true

# Replace the '❯' symbol in the prompt with '➜'
[character] # The name of the module we are configuring is 'character'
success_symbol = '[➜](bold green)' # The 'success_symbol' segment is being set to '➜' with the color 'bold green'

# Disable the package module, hiding it from the prompt completely
[package]
disabled = true

[username]
style_user='fg:#43cc71 bg:#303030'
format='[$user@]($style)'
show_always=true

[hostname]
style='fg:#43cc71 bg:#303030'
format='[$hostname:]($style)'
ssh_only=false
disabled=false

[directory]
style='fg:#CDCDCD bg:#444444'
read_only_style='fg:red bg:#002424'
truncation_symbol='.../'
format='[$path]($style)[$read_only]($read_only_style)'

[git_branch]
style='fg:white bg:#053354'
format='[ $symbol$branch(:$remote_branch)]($style)'

[git_metrics]
added_style='bold fg:green bg:#053354'
deleted_style='bold fg:red bg:#053354'

[git_status]
style='bold fg:red bg:#053354'
format='([ \[$all_status$ahead_behind\]]($style))'


